### ISSUE TITLE
2.0 UX

### ISSUE THREAD

**Issue by n13** [n13/Recognition#1]
Nico just told me the solution to our on/off screen woes and the settings screen

1 - There will be two screens - closed state and open state
2 - The first screen will show, unmistakably, that reminders are now enabled. It will show what the settings are set to, and have an on/off button and a "change settings" button.
3 - The second screen will be to change settings, and will look like our main screen now, but have a "Done" button (easiest to do with a nav bar upper right hand corner button)
3a - Settings in the second screen will change in-line. The separate "Settings" screen we have now will be gone. So for example, changing the time will use standard UX elements like time rollers that spring up from the bottom.

I think it'll be good to have a screen with the sole purpose of showing that the app is running, and reading out what it's doing.

Nico pointed out to me that on the current design it's not obvious whether or not the app is running right now. Users would ask themselves - is that it?

He also wanted some start screens to create the initial settings, like a guided tour. How many reminders per day, when do you get up, when do you go to sleep (or want to stop reminders).

I think that would be pretty much perfect. then we don't have the off state screen issue we have now, and the app will be better in that it's 100% clear what is happening. 

Yury: tell me what you think about it. As always in this project, strong opinions are encouraged ;)

I think the advantage on the current design is that it's only 2 screens and fits well together. We can slightly modify the current "Off screen" design to achieve this. 

Nico: Does that cover it?

**Comment by n13** [comment]
![1](https://cloud.githubusercontent.com/assets/65412/13315323/b87f5604-dbdc-11e5-92cc-46bf7db27a28.jpg)
![2](https://cloud.githubusercontent.com/assets/65412/13315324/b880a5cc-dbdc-11e5-9b96-6cfebbea0084.jpg)
![3](https://cloud.githubusercontent.com/assets/65412/13315325/b8814fea-dbdc-11e5-9a4b-82aa371e56d6.jpg)
mockups

**Comment by ytspar** [comment]
@n13, moving your comments from the email here (also, there's a channel on http://mvgchat.slack.com for #recognition, if you want to use Slack):

> (I'm in Beijing everything is blocked here... even gmail)

Hah, _especially_ Google is blocked.

> Uploaded a new build - it's pretty close to UX2.0 - but not quite.

Is this on TestFlight? I'm not clear on how to pull the latest builds.

> One issue is numbers: There seems to be absolutely NO way to get them as close together as they are in the design. Not with HelveticaNeue anyway.
> 
> I reduced the kerning and that puts them closer together, but that eventually runs into problems where the numbers no longer render correctly. 

I noted this on Zeplin, but there shouldn't be any reason not to use SF UI fonts for the numbers. It's kind of a pain to only modify part of a string in Sketch, but I've done some quick tests locally and the SF UI ("text," not "display") numbers blend in fine with Helvetica text.

> Known issues:
> - Fonts don't look exactly like design even though I used the same settings, e.g. same size, same weight, same font, same color

Can you send the new build or screenshots from it? I can overlay on top of the mocks and see what's up. 

> - Numbers specifically are totally off

Solvable, I think!

> - Settings screen necessarily has a top bar and a done button. I am open to other suggestions but... it needs a done / dismiss button.

This got me thinking. The workflow changed, with the addition of the two new screens, so the on/off toggle on the edit view is no longer needed.

![iphone 6 - v3](https://cloud.githubusercontent.com/assets/365593/13421524/72675a98-dfc1-11e5-9a62-e52d3550275f.png)

This makes more sense to me now. 

**!** I can't seem to get this uploaded to Zeplin: 

`Could not export dartboards 😞 - ☝️ Looks like this error is caused by the font "AppleColorEmoji". Try changing the fonts of your emoji text layers to another font, save the document (⌘ + S) and try again.`

wtf

> To test:
> - Check into editing the reminder text - this is new, it's in-line. It's supposed to scroll up which works, more or less, but has some stupid issue when adding/removing lines
> - number of reminders and dates edit inline, and update the settings right away. The "cancel" buttons on the pickers are not working, e.g. the settings are applied immediately. I Think that's the way to go, will remove the cancel button.

**Comment by n13** [comment]
Released 1.0.4 build - I thought that build would automatically go to beta when I upload, but apparently for external testers they don't...

```
N.
```

**Comment by ytspar** [comment]
![nik-design_sketch](https://cloud.githubusercontent.com/assets/365593/13422285/615fe88c-dfc6-11e5-9c8c-021a28171176.png)

**Comment by ytspar** [comment]
Since I still can't push to Zeplin, I'll add the latest screenshots here:

More consistency in layouts (important now that I've seen the animations between states):

![nik-design_sketch](https://cloud.githubusercontent.com/assets/365593/13422420/4c893f98-dfc7-11e5-9389-f30cf944642e.png)

---

The screens themselves, at 1x:

![edit reminders 1x](https://cloud.githubusercontent.com/assets/365593/13422431/5ee8f304-dfc7-11e5-9f7f-958dfb3d13f1.png)
![iphone 6 - v3 - reminders off 1x](https://cloud.githubusercontent.com/assets/365593/13422432/5ef94d62-dfc7-11e5-9da3-89e055f35d63.png)
![iphone 6 - v3 - reminders on 1x](https://cloud.githubusercontent.com/assets/365593/13422433/5f4a5216-dfc7-11e5-9902-7b59ba3d0507.png)

**Comment by ytspar** [comment]
Rethinking this.

**Comment by ytspar** [comment]
Thinking, more like this:

![fullscreen_3_1_16__7_38_pm](https://cloud.githubusercontent.com/assets/365593/13427224/2b7866bc-dfe5-11e5-919f-ea88fa5d0534.png)

Notes:

![fullscreen_3_1_16__7_38_pm](https://cloud.githubusercontent.com/assets/365593/13427286/8e45802c-dfe5-11e5-80a4-32fda086a93c.png)

Individual screenshots:

![iphone 6 - v3 - reminders off](https://cloud.githubusercontent.com/assets/365593/13427292/992c4fe8-dfe5-11e5-8dbc-207664d974fd.png)

![iphone 6 - v3 - reminders on](https://cloud.githubusercontent.com/assets/365593/13427294/9df9839c-dfe5-11e5-88dc-768db92776f6.png)

![edit reminders](https://cloud.githubusercontent.com/assets/365593/13427304/ab318b90-dfe5-11e5-9756-356179467b12.png)

**Comment by ytspar** [comment]
Tweaked and pushed to Zeplin (successfully)!

**Comment by n13** [comment]
One thing that kinda sucks about zeplin: No offline mode.

Like it doesn't work at all offline, not even showing things it already downloaded

But other than that... cool

**Comment by ytspar** [comment]
Yeah, it's a wrapper for a web view, I think. 

I've cleaned up the Sketch file (better labeling, grouping, labeling - this is good to go for a public release, if need be) and made the relevant assets exportable via Zeplin and modified the workflow slightly, for consistency:

![nik-design_sketch](https://cloud.githubusercontent.com/assets/365593/13457161/4214868a-e099-11e5-9dca-a9db4c084ca7.png)

![nik-design_sketch](https://cloud.githubusercontent.com/assets/365593/13457266/ce166ea0-e099-11e5-99ac-3a317a036d77.png)

**Comment by ytspar** [comment]
**Workflow**

![workflow](https://cloud.githubusercontent.com/assets/365593/13468804/1a3b4dd6-e0d7-11e5-8c9c-dbae1d25b59f.png)

_Zeplin updated_

**Comment by ytspar** [comment]
OK, Zeplin updated significantly - all relevant assets are exportable (let me know if you need the lines and dividers in an exportable format, too). Even mopped up the document structure.

![nik-design_sketch_and_flowchart-webdesign-kit-dimitrifrompari_sketch](https://cloud.githubusercontent.com/assets/365593/13471213/2b9bf890-e0e2-11e5-833e-c3c19a74de1b.png)

**Comment by ytspar** [comment]
Site's done!

![site](https://cloud.githubusercontent.com/assets/365593/13616506/c0ec895e-e5ac-11e5-9da4-34af6063003a.gif)

The code isn't exactly elegant, but it works (at least in Chrome and Safari).

**Comment by ytspar** [comment]
## To do
- [ ] Replace the screenshots when I get final copy for home screen 
- [ ] Add more detailed copy to bottom of page (@n13, as we spoke about, creating at least an outline - why you would want to do this, some of the details your woo woo expert sent)
- [ ] Put it up on a custom domain - I can do this with AWS S3 or Github pages. The base I used is built around Github pages, so that's my preference.
- [ ] Mop up some of the cruft (I started using some frameworks, dumped them; there's probably some stuff left over), optimize the build. Probably not needed.
- [ ] Working App Store link
- [ ] Customize README (right now it's the Thoughtbot template default)

Website is here: https://github.com/ytspar/recognitionsite

**Comment by n13** [comment]
Super cool!!!

One thing though, I am going to only have 2 screens - the status screen and the settings screen. I am not sure what/why the first screen is ... but I am pretty sure we should have 2 ;)

I showed the app to Bentinho in Maui and got some tentative approval. And found a way to release this and also work for them, so ... yeah, baby!

```
Nik
```

**Comment by n13** [comment]
This rocks man!

**Comment by ytspar** [comment]
@n13 that's cool!

Yeah, the screenshots will be of whatever the app turns out like. I'd actually prefer one screenshot, animated.

**Comment by ytspar** [comment]
@n13 that's cool!

Yeah, the screenshots will be of whatever the app turns out like. I'd actually prefer one screenshot, animated.

**Comment by ytspar** [comment]
@n13 that's cool!

Yeah, the screenshots will be of whatever the app turns out like. I'd actually prefer one screenshot, animated.

**Comment by ytspar** [comment]
I made an animation for kicks, but it's missing smooth transitions. 

![animation](https://cloud.githubusercontent.com/assets/365593/13673626/84105cde-e70c-11e5-8e0b-4605fdc4c5ec.gif)

**Comment by n13** [comment]
old ticket, retiring
